create table products (
    id bigint generated by default as identity primary key,
    name varchar(255),
    description varchar(255),
    price numeric(38,2),
    category varchar(255),
    in_stock boolean not null
);
