create table inventories (
    id bigint generated by default as identity primary key,
    product_id bigint not null unique,
    quantity integer not null default 0,
    reserved_quantity integer not null default 0,
    constraint fk_inventories_product
        foreign key (product_id) references products (id),
    constraint chk_inventories_quantity
        check (quantity >= 0),
    constraint chk_inventories_reserved_quantity
        check (reserved_quantity >= 0),
    constraint chk_inventories_reserved_not_greater_than_quantity
        check (reserved_quantity <= quantity)
);
